auctionItems = [
    "Chair sat on by Albert Einstein",
    "Soccer ball", 
    "4K OLED 65 inch TV",
    "Gucci shirt",
    "Coach Purse",
    "Kate Spade Purse", 
    "George Washington Original Letters",
    "Spongebob Entire TV Collection",
    "Fake vomit", 
    "Sword of Alexander the Great",
    "Can of iced cold Pepsi", 
    "Can of iced cold Coca Cola",
    "Korean Barbecue pass for a month",
    "Trip to Paris",
    "Tesla Model S",
    "Tickets to see your favorite sports team",
    "Tickets to see your favorite musician",
    "Trip to London",
    "Bose headphones", 
    "Trip to Madrid",
    "Abiity to fly for a day",
    "Warm winter socks",
    "Beach volleyball",
    "Ability to read someone's mind for a week",
    "Trip to Bora Bora"
]